// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: proto/mcp_extension.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	McpExtensionService_SearchDiary_FullMethodName  = "/mcp.extension.McpExtensionService/SearchDiary"
	McpExtensionService_SearchMemory_FullMethodName = "/mcp.extension.McpExtensionService/SearchMemory"
)

// McpExtensionServiceClient is the client API for McpExtensionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type McpExtensionServiceClient interface {
	// Searches diaries by keyword and time range
	SearchDiary(ctx context.Context, in *SearchDiaryRequest, opts ...grpc.CallOption) (*SearchDiaryResponse, error)
	// Searches memories including mid-term memories and short-term conversation context
	SearchMemory(ctx context.Context, in *SearchMemoryRequest, opts ...grpc.CallOption) (*SearchMemoryResponse, error)
}

type mcpExtensionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMcpExtensionServiceClient(cc grpc.ClientConnInterface) McpExtensionServiceClient {
	return &mcpExtensionServiceClient{cc}
}

func (c *mcpExtensionServiceClient) SearchDiary(ctx context.Context, in *SearchDiaryRequest, opts ...grpc.CallOption) (*SearchDiaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchDiaryResponse)
	err := c.cc.Invoke(ctx, McpExtensionService_SearchDiary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mcpExtensionServiceClient) SearchMemory(ctx context.Context, in *SearchMemoryRequest, opts ...grpc.CallOption) (*SearchMemoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchMemoryResponse)
	err := c.cc.Invoke(ctx, McpExtensionService_SearchMemory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// McpExtensionServiceServer is the server API for McpExtensionService service.
// All implementations must embed UnimplementedMcpExtensionServiceServer
// for forward compatibility.
type McpExtensionServiceServer interface {
	// Searches diaries by keyword and time range
	SearchDiary(context.Context, *SearchDiaryRequest) (*SearchDiaryResponse, error)
	// Searches memories including mid-term memories and short-term conversation context
	SearchMemory(context.Context, *SearchMemoryRequest) (*SearchMemoryResponse, error)
	mustEmbedUnimplementedMcpExtensionServiceServer()
}

// UnimplementedMcpExtensionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMcpExtensionServiceServer struct{}

func (UnimplementedMcpExtensionServiceServer) SearchDiary(context.Context, *SearchDiaryRequest) (*SearchDiaryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchDiary not implemented")
}
func (UnimplementedMcpExtensionServiceServer) SearchMemory(context.Context, *SearchMemoryRequest) (*SearchMemoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchMemory not implemented")
}
func (UnimplementedMcpExtensionServiceServer) mustEmbedUnimplementedMcpExtensionServiceServer() {}
func (UnimplementedMcpExtensionServiceServer) testEmbeddedByValue()                             {}

// UnsafeMcpExtensionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to McpExtensionServiceServer will
// result in compilation errors.
type UnsafeMcpExtensionServiceServer interface {
	mustEmbedUnimplementedMcpExtensionServiceServer()
}

func RegisterMcpExtensionServiceServer(s grpc.ServiceRegistrar, srv McpExtensionServiceServer) {
	// If the following call panics, it indicates UnimplementedMcpExtensionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&McpExtensionService_ServiceDesc, srv)
}

func _McpExtensionService_SearchDiary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchDiaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McpExtensionServiceServer).SearchDiary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: McpExtensionService_SearchDiary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McpExtensionServiceServer).SearchDiary(ctx, req.(*SearchDiaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _McpExtensionService_SearchMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchMemoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McpExtensionServiceServer).SearchMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: McpExtensionService_SearchMemory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McpExtensionServiceServer).SearchMemory(ctx, req.(*SearchMemoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// McpExtensionService_ServiceDesc is the grpc.ServiceDesc for McpExtensionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var McpExtensionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mcp.extension.McpExtensionService",
	HandlerType: (*McpExtensionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchDiary",
			Handler:    _McpExtensionService_SearchDiary_Handler,
		},
		{
			MethodName: "SearchMemory",
			Handler:    _McpExtensionService_SearchMemory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/mcp_extension.proto",
}
