// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/mcp_extension.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchDiaryRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	ApiKey  string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Keyword string                 `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`
	// Format: yyyy-MM-dd HH:mm:ss. Can be empty.
	StartTime string `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// Format: yyyy-MM-dd HH:mm:ss. Can be empty.
	EndTime       string `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchDiaryRequest) Reset() {
	*x = SearchDiaryRequest{}
	mi := &file_proto_mcp_extension_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchDiaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchDiaryRequest) ProtoMessage() {}

func (x *SearchDiaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_extension_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchDiaryRequest.ProtoReflect.Descriptor instead.
func (*SearchDiaryRequest) Descriptor() ([]byte, []int) {
	return file_proto_mcp_extension_proto_rawDescGZIP(), []int{0}
}

func (x *SearchDiaryRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *SearchDiaryRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SearchDiaryRequest) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *SearchDiaryRequest) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

type SearchDiaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*DiaryResult         `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchDiaryResponse) Reset() {
	*x = SearchDiaryResponse{}
	mi := &file_proto_mcp_extension_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchDiaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchDiaryResponse) ProtoMessage() {}

func (x *SearchDiaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_extension_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchDiaryResponse.ProtoReflect.Descriptor instead.
func (*SearchDiaryResponse) Descriptor() ([]byte, []int) {
	return file_proto_mcp_extension_proto_rawDescGZIP(), []int{1}
}

func (x *SearchDiaryResponse) GetResults() []*DiaryResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SearchDiaryResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type DiaryResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DiaryId       string                 `protobuf:"bytes,1,opt,name=diary_id,json=diaryId,proto3" json:"diary_id,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Emotion       string                 `protobuf:"bytes,4,opt,name=emotion,proto3" json:"emotion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiaryResult) Reset() {
	*x = DiaryResult{}
	mi := &file_proto_mcp_extension_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiaryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiaryResult) ProtoMessage() {}

func (x *DiaryResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_extension_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiaryResult.ProtoReflect.Descriptor instead.
func (*DiaryResult) Descriptor() ([]byte, []int) {
	return file_proto_mcp_extension_proto_rawDescGZIP(), []int{2}
}

func (x *DiaryResult) GetDiaryId() string {
	if x != nil {
		return x.DiaryId
	}
	return ""
}

func (x *DiaryResult) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *DiaryResult) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *DiaryResult) GetEmotion() string {
	if x != nil {
		return x.Emotion
	}
	return ""
}

type SearchMemoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	MaxResults    int32                  `protobuf:"varint,3,opt,name=max_results,json=maxResults,proto3" json:"max_results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchMemoryRequest) Reset() {
	*x = SearchMemoryRequest{}
	mi := &file_proto_mcp_extension_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchMemoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMemoryRequest) ProtoMessage() {}

func (x *SearchMemoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_extension_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchMemoryRequest.ProtoReflect.Descriptor instead.
func (*SearchMemoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_mcp_extension_proto_rawDescGZIP(), []int{3}
}

func (x *SearchMemoryRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *SearchMemoryRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchMemoryRequest) GetMaxResults() int32 {
	if x != nil {
		return x.MaxResults
	}
	return 0
}

type SearchMemoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*MemoryResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchMemoryResponse) Reset() {
	*x = SearchMemoryResponse{}
	mi := &file_proto_mcp_extension_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchMemoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMemoryResponse) ProtoMessage() {}

func (x *SearchMemoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_extension_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchMemoryResponse.ProtoReflect.Descriptor instead.
func (*SearchMemoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_mcp_extension_proto_rawDescGZIP(), []int{4}
}

func (x *SearchMemoryResponse) GetResults() []*MemoryResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SearchMemoryResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type MemoryResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // MID_TERM_MEMORY or SHORT_TERM_CONTEXT
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	SourceId      string                 `protobuf:"bytes,3,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`    // memory id or message id
	Score         float64                `protobuf:"fixed64,4,opt,name=score,proto3" json:"score,omitempty"`                        // relevance score
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // creation time
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryResult) Reset() {
	*x = MemoryResult{}
	mi := &file_proto_mcp_extension_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryResult) ProtoMessage() {}

func (x *MemoryResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_extension_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryResult.ProtoReflect.Descriptor instead.
func (*MemoryResult) Descriptor() ([]byte, []int) {
	return file_proto_mcp_extension_proto_rawDescGZIP(), []int{5}
}

func (x *MemoryResult) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MemoryResult) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MemoryResult) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *MemoryResult) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *MemoryResult) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_proto_mcp_extension_proto protoreflect.FileDescriptor

const file_proto_mcp_extension_proto_rawDesc = "" +
	"\n" +
	"\x19proto/mcp_extension.proto\x12\rmcp.extension\"\x81\x01\n" +
	"\x12SearchDiaryRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x18\n" +
	"\akeyword\x18\x02 \x01(\tR\akeyword\x12\x1d\n" +
	"\n" +
	"start_time\x18\x03 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x04 \x01(\tR\aendTime\"p\n" +
	"\x13SearchDiaryResponse\x124\n" +
	"\aresults\x18\x01 \x03(\v2\x1a.mcp.extension.DiaryResultR\aresults\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"p\n" +
	"\vDiaryResult\x12\x19\n" +
	"\bdiary_id\x18\x01 \x01(\tR\adiaryId\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x18\n" +
	"\aemotion\x18\x04 \x01(\tR\aemotion\"e\n" +
	"\x13SearchMemoryRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\x1f\n" +
	"\vmax_results\x18\x03 \x01(\x05R\n" +
	"maxResults\"r\n" +
	"\x14SearchMemoryResponse\x125\n" +
	"\aresults\x18\x01 \x03(\v2\x1b.mcp.extension.MemoryResultR\aresults\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\x8e\x01\n" +
	"\fMemoryResult\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1b\n" +
	"\tsource_id\x18\x03 \x01(\tR\bsourceId\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x01R\x05score\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt2\xc8\x01\n" +
	"\x13McpExtensionService\x12V\n" +
	"\vSearchDiary\x12!.mcp.extension.SearchDiaryRequest\x1a\".mcp.extension.SearchDiaryResponse\"\x00\x12Y\n" +
	"\fSearchMemory\x12\".mcp.extension.SearchMemoryRequest\x1a#.mcp.extension.SearchMemoryResponse\"\x00B;\n" +
	"\x19com.aseubel.yusi.grpc.mcpB\x11McpExtensionProtoP\x01Z\tmcp/protob\x06proto3"

var (
	file_proto_mcp_extension_proto_rawDescOnce sync.Once
	file_proto_mcp_extension_proto_rawDescData []byte
)

func file_proto_mcp_extension_proto_rawDescGZIP() []byte {
	file_proto_mcp_extension_proto_rawDescOnce.Do(func() {
		file_proto_mcp_extension_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_mcp_extension_proto_rawDesc), len(file_proto_mcp_extension_proto_rawDesc)))
	})
	return file_proto_mcp_extension_proto_rawDescData
}

var file_proto_mcp_extension_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_mcp_extension_proto_goTypes = []any{
	(*SearchDiaryRequest)(nil),   // 0: mcp.extension.SearchDiaryRequest
	(*SearchDiaryResponse)(nil),  // 1: mcp.extension.SearchDiaryResponse
	(*DiaryResult)(nil),          // 2: mcp.extension.DiaryResult
	(*SearchMemoryRequest)(nil),  // 3: mcp.extension.SearchMemoryRequest
	(*SearchMemoryResponse)(nil), // 4: mcp.extension.SearchMemoryResponse
	(*MemoryResult)(nil),         // 5: mcp.extension.MemoryResult
}
var file_proto_mcp_extension_proto_depIdxs = []int32{
	2, // 0: mcp.extension.SearchDiaryResponse.results:type_name -> mcp.extension.DiaryResult
	5, // 1: mcp.extension.SearchMemoryResponse.results:type_name -> mcp.extension.MemoryResult
	0, // 2: mcp.extension.McpExtensionService.SearchDiary:input_type -> mcp.extension.SearchDiaryRequest
	3, // 3: mcp.extension.McpExtensionService.SearchMemory:input_type -> mcp.extension.SearchMemoryRequest
	1, // 4: mcp.extension.McpExtensionService.SearchDiary:output_type -> mcp.extension.SearchDiaryResponse
	4, // 5: mcp.extension.McpExtensionService.SearchMemory:output_type -> mcp.extension.SearchMemoryResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_mcp_extension_proto_init() }
func file_proto_mcp_extension_proto_init() {
	if File_proto_mcp_extension_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_mcp_extension_proto_rawDesc), len(file_proto_mcp_extension_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_mcp_extension_proto_goTypes,
		DependencyIndexes: file_proto_mcp_extension_proto_depIdxs,
		MessageInfos:      file_proto_mcp_extension_proto_msgTypes,
	}.Build()
	File_proto_mcp_extension_proto = out.File
	file_proto_mcp_extension_proto_goTypes = nil
	file_proto_mcp_extension_proto_depIdxs = nil
}
