// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v6.33.2
// source: proto/mcp_extension.proto

package mcp_extension

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchDiaryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Keyword string `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`
	// Format: yyyy-MM-dd HH:mm:ss. Can be empty.
	StartTime string `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// Format: yyyy-MM-dd HH:mm:ss. Can be empty.
	EndTime string `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
}

func (x *SearchDiaryRequest) Reset() {
	*x = SearchDiaryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mcp_extension_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchDiaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchDiaryRequest) ProtoMessage() {}

func (x *SearchDiaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_extension_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchDiaryRequest.ProtoReflect.Descriptor instead.
func (*SearchDiaryRequest) Descriptor() ([]byte, []int) {
	return file_proto_mcp_extension_proto_rawDescGZIP(), []int{0}
}

func (x *SearchDiaryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SearchDiaryRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SearchDiaryRequest) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *SearchDiaryRequest) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

type SearchDiaryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results      []*DiaryResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	ErrorMessage string         `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
}

func (x *SearchDiaryResponse) Reset() {
	*x = SearchDiaryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mcp_extension_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchDiaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchDiaryResponse) ProtoMessage() {}

func (x *SearchDiaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_extension_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchDiaryResponse.ProtoReflect.Descriptor instead.
func (*SearchDiaryResponse) Descriptor() ([]byte, []int) {
	return file_proto_mcp_extension_proto_rawDescGZIP(), []int{1}
}

func (x *SearchDiaryResponse) GetResults() []*DiaryResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SearchDiaryResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type DiaryResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DiaryId string `protobuf:"bytes,1,opt,name=diary_id,json=diaryId,proto3" json:"diary_id,omitempty"`
	Date    string `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Content string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Emotion string `protobuf:"bytes,4,opt,name=emotion,proto3" json:"emotion,omitempty"`
}

func (x *DiaryResult) Reset() {
	*x = DiaryResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mcp_extension_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiaryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiaryResult) ProtoMessage() {}

func (x *DiaryResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_extension_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiaryResult.ProtoReflect.Descriptor instead.
func (*DiaryResult) Descriptor() ([]byte, []int) {
	return file_proto_mcp_extension_proto_rawDescGZIP(), []int{2}
}

func (x *DiaryResult) GetDiaryId() string {
	if x != nil {
		return x.DiaryId
	}
	return ""
}

func (x *DiaryResult) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *DiaryResult) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *DiaryResult) GetEmotion() string {
	if x != nil {
		return x.Emotion
	}
	return ""
}

type QueryLifeGraphRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Query  string `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *QueryLifeGraphRequest) Reset() {
	*x = QueryLifeGraphRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mcp_extension_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryLifeGraphRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryLifeGraphRequest) ProtoMessage() {}

func (x *QueryLifeGraphRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_extension_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryLifeGraphRequest.ProtoReflect.Descriptor instead.
func (*QueryLifeGraphRequest) Descriptor() ([]byte, []int) {
	return file_proto_mcp_extension_proto_rawDescGZIP(), []int{3}
}

func (x *QueryLifeGraphRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *QueryLifeGraphRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type QueryLifeGraphResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResultJson   string `protobuf:"bytes,1,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	ErrorMessage string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
}

func (x *QueryLifeGraphResponse) Reset() {
	*x = QueryLifeGraphResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mcp_extension_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryLifeGraphResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryLifeGraphResponse) ProtoMessage() {}

func (x *QueryLifeGraphResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_extension_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryLifeGraphResponse.ProtoReflect.Descriptor instead.
func (*QueryLifeGraphResponse) Descriptor() ([]byte, []int) {
	return file_proto_mcp_extension_proto_rawDescGZIP(), []int{4}
}

func (x *QueryLifeGraphResponse) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

func (x *QueryLifeGraphResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_proto_mcp_extension_proto protoreflect.FileDescriptor

var file_proto_mcp_extension_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x63, 0x70, 0x5f, 0x65, 0x78, 0x74, 0x65,
	0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x6d, 0x63, 0x70,
	0x2e, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x81, 0x01, 0x0a, 0x12, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x44, 0x69, 0x61, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6b, 0x65,
	0x79, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6b, 0x65, 0x79,
	0x77, 0x6f, 0x72, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x70,
	0x0a, 0x13, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x44, 0x69, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6d, 0x63, 0x70, 0x2e, 0x65, 0x78, 0x74,
	0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x44, 0x69, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x22, 0x70, 0x0a, 0x0b, 0x44, 0x69, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x19, 0x0a, 0x08, 0x64, 0x69, 0x61, 0x72, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x64, 0x69, 0x61, 0x72, 0x79, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6d, 0x6f, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x6d, 0x6f, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0x46, 0x0a, 0x15, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4c, 0x69, 0x66, 0x65, 0x47,
	0x72, 0x61, 0x70, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x22, 0x5e, 0x0a, 0x16, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x4c, 0x69, 0x66, 0x65, 0x47, 0x72, 0x61, 0x70, 0x68, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x5f, 0x6a,
	0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x4a, 0x73, 0x6f, 0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0xce, 0x01, 0x0a, 0x13, 0x4d,
	0x63, 0x70, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x56, 0x0a, 0x0b, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x44, 0x69, 0x61, 0x72,
	0x79, 0x12, 0x21, 0x2e, 0x6d, 0x63, 0x70, 0x2e, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f,
	0x6e, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x44, 0x69, 0x61, 0x72, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x6d, 0x63, 0x70, 0x2e, 0x65, 0x78, 0x74, 0x65, 0x6e,
	0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x44, 0x69, 0x61, 0x72, 0x79,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5f, 0x0a, 0x0e, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x4c, 0x69, 0x66, 0x65, 0x47, 0x72, 0x61, 0x70, 0x68, 0x12, 0x24, 0x2e, 0x6d,
	0x63, 0x70, 0x2e, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x4c, 0x69, 0x66, 0x65, 0x47, 0x72, 0x61, 0x70, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x25, 0x2e, 0x6d, 0x63, 0x70, 0x2e, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69,
	0x6f, 0x6e, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4c, 0x69, 0x66, 0x65, 0x47, 0x72, 0x61, 0x70,
	0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x56, 0x0a, 0x19, 0x63,
	0x6f, 0x6d, 0x2e, 0x61, 0x73, 0x65, 0x75, 0x62, 0x65, 0x6c, 0x2e, 0x79, 0x75, 0x73, 0x69, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x6d, 0x63, 0x70, 0x42, 0x11, 0x4d, 0x63, 0x70, 0x45, 0x78, 0x74,
	0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x24, 0x79,
	0x75, 0x73, 0x69, 0x2f, 0x6d, 0x63, 0x70, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x6d, 0x63, 0x70, 0x5f, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73,
	0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_mcp_extension_proto_rawDescOnce sync.Once
	file_proto_mcp_extension_proto_rawDescData = file_proto_mcp_extension_proto_rawDesc
)

func file_proto_mcp_extension_proto_rawDescGZIP() []byte {
	file_proto_mcp_extension_proto_rawDescOnce.Do(func() {
		file_proto_mcp_extension_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_mcp_extension_proto_rawDescData)
	})
	return file_proto_mcp_extension_proto_rawDescData
}

var file_proto_mcp_extension_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_mcp_extension_proto_goTypes = []interface{}{
	(*SearchDiaryRequest)(nil),     // 0: mcp.extension.SearchDiaryRequest
	(*SearchDiaryResponse)(nil),    // 1: mcp.extension.SearchDiaryResponse
	(*DiaryResult)(nil),            // 2: mcp.extension.DiaryResult
	(*QueryLifeGraphRequest)(nil),  // 3: mcp.extension.QueryLifeGraphRequest
	(*QueryLifeGraphResponse)(nil), // 4: mcp.extension.QueryLifeGraphResponse
}
var file_proto_mcp_extension_proto_depIdxs = []int32{
	2, // 0: mcp.extension.SearchDiaryResponse.results:type_name -> mcp.extension.DiaryResult
	0, // 1: mcp.extension.McpExtensionService.SearchDiary:input_type -> mcp.extension.SearchDiaryRequest
	3, // 2: mcp.extension.McpExtensionService.QueryLifeGraph:input_type -> mcp.extension.QueryLifeGraphRequest
	1, // 3: mcp.extension.McpExtensionService.SearchDiary:output_type -> mcp.extension.SearchDiaryResponse
	4, // 4: mcp.extension.McpExtensionService.QueryLifeGraph:output_type -> mcp.extension.QueryLifeGraphResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_mcp_extension_proto_init() }
func file_proto_mcp_extension_proto_init() {
	if File_proto_mcp_extension_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_mcp_extension_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchDiaryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mcp_extension_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchDiaryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mcp_extension_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiaryResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mcp_extension_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryLifeGraphRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mcp_extension_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryLifeGraphResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_mcp_extension_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_mcp_extension_proto_goTypes,
		DependencyIndexes: file_proto_mcp_extension_proto_depIdxs,
		MessageInfos:      file_proto_mcp_extension_proto_msgTypes,
	}.Build()
	File_proto_mcp_extension_proto = out.File
	file_proto_mcp_extension_proto_rawDesc = nil
	file_proto_mcp_extension_proto_goTypes = nil
	file_proto_mcp_extension_proto_depIdxs = nil
}
