// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v6.33.2
// source: proto/mcp_extension.proto

package mcp_extension

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// McpExtensionServiceClient is the client API for McpExtensionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type McpExtensionServiceClient interface {
	// Searches diaries by keyword and time range
	SearchDiary(ctx context.Context, in *SearchDiaryRequest, opts ...grpc.CallOption) (*SearchDiaryResponse, error)
	// Queries the life graph
	QueryLifeGraph(ctx context.Context, in *QueryLifeGraphRequest, opts ...grpc.CallOption) (*QueryLifeGraphResponse, error)
}

type mcpExtensionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMcpExtensionServiceClient(cc grpc.ClientConnInterface) McpExtensionServiceClient {
	return &mcpExtensionServiceClient{cc}
}

func (c *mcpExtensionServiceClient) SearchDiary(ctx context.Context, in *SearchDiaryRequest, opts ...grpc.CallOption) (*SearchDiaryResponse, error) {
	out := new(SearchDiaryResponse)
	err := c.cc.Invoke(ctx, "/mcp.extension.McpExtensionService/SearchDiary", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mcpExtensionServiceClient) QueryLifeGraph(ctx context.Context, in *QueryLifeGraphRequest, opts ...grpc.CallOption) (*QueryLifeGraphResponse, error) {
	out := new(QueryLifeGraphResponse)
	err := c.cc.Invoke(ctx, "/mcp.extension.McpExtensionService/QueryLifeGraph", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// McpExtensionServiceServer is the server API for McpExtensionService service.
// All implementations must embed UnimplementedMcpExtensionServiceServer
// for forward compatibility
type McpExtensionServiceServer interface {
	// Searches diaries by keyword and time range
	SearchDiary(context.Context, *SearchDiaryRequest) (*SearchDiaryResponse, error)
	// Queries the life graph
	QueryLifeGraph(context.Context, *QueryLifeGraphRequest) (*QueryLifeGraphResponse, error)
	mustEmbedUnimplementedMcpExtensionServiceServer()
}

// UnimplementedMcpExtensionServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMcpExtensionServiceServer struct {
}

func (UnimplementedMcpExtensionServiceServer) SearchDiary(context.Context, *SearchDiaryRequest) (*SearchDiaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchDiary not implemented")
}
func (UnimplementedMcpExtensionServiceServer) QueryLifeGraph(context.Context, *QueryLifeGraphRequest) (*QueryLifeGraphResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryLifeGraph not implemented")
}
func (UnimplementedMcpExtensionServiceServer) mustEmbedUnimplementedMcpExtensionServiceServer() {}

// UnsafeMcpExtensionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to McpExtensionServiceServer will
// result in compilation errors.
type UnsafeMcpExtensionServiceServer interface {
	mustEmbedUnimplementedMcpExtensionServiceServer()
}

func RegisterMcpExtensionServiceServer(s grpc.ServiceRegistrar, srv McpExtensionServiceServer) {
	s.RegisterService(&McpExtensionService_ServiceDesc, srv)
}

func _McpExtensionService_SearchDiary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchDiaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McpExtensionServiceServer).SearchDiary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mcp.extension.McpExtensionService/SearchDiary",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McpExtensionServiceServer).SearchDiary(ctx, req.(*SearchDiaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _McpExtensionService_QueryLifeGraph_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLifeGraphRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McpExtensionServiceServer).QueryLifeGraph(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mcp.extension.McpExtensionService/QueryLifeGraph",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McpExtensionServiceServer).QueryLifeGraph(ctx, req.(*QueryLifeGraphRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// McpExtensionService_ServiceDesc is the grpc.ServiceDesc for McpExtensionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var McpExtensionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mcp.extension.McpExtensionService",
	HandlerType: (*McpExtensionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchDiary",
			Handler:    _McpExtensionService_SearchDiary_Handler,
		},
		{
			MethodName: "QueryLifeGraph",
			Handler:    _McpExtensionService_QueryLifeGraph_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/mcp_extension.proto",
}
